//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.Professor_Subjects = new HashSet<Professor_Subject>();
            this.Student_Subjects = new HashSet<Student_Subject>();
            this.Subjects1 = new HashSet<Subject>();
        }
    
        public int id { get; set; }
        public string subject1 { get; set; }
        public double creditHours { get; set; }
        public string code { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> deptId_FK { get; set; }
        public Nullable<int> preSubjectId_FK { get; set; }
        public string day { get; set; }
        public Nullable<System.TimeSpan> fromTime { get; set; }
        public Nullable<System.TimeSpan> toTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor_Subject> Professor_Subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Subject> Student_Subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects1 { get; set; }
        public virtual Subject Subject2 { get; set; }
    }
}
